# copy from k8-resources--> 16-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # labels of deployment resource
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
# pod template
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: poojarivinod1/app1:1.0.0
        ports: 
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector: # labels are used as selectors, it connects to that pod
    app: app1
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # target container port
    